import Head from 'next/head';

import axios from '~services/index';
import { useQuery } from '@tanstack/react-query';

export default function Home() {
  useQuery(
    ['fetchData'],
    () => {
      return axios.get('/welcome');
    },
    {
      onSuccess: (data) => {
        console.log(data);
      },
    }
  );

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>This is Body</main>
    </>
  );
}
